run:
  skip-files:
    - doc.go
    - ".*\\.pb\\.go$"
  skip-dirs:
    - frontend  
  timeout: 5m
  tests: true  
linters:
  enable:
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/kiali/kiali
